### ISSUE TITLE
Latest build (downloaded July 15, 2024) has incorrect System.Text.Json package

### ISSUE THREAD

**Issue by ajmiam** [tge-was-taken/Atlus-Script-Tools#81]
My operating system is Windows 10.

I just downloaded the latest build linked in the readme from here: https://ci.appveyor.com/project/tge-was-taken/atlus-script-tools/build/artifacts

Running it, I get the error below. Note that the message indicates it's looking for a System.Text.Json DLL with a version of 8.0.0.4, but the one included in the build artifact is 8.0.23.53103 according to File Explorer's Properties dialog.

Does the linked build not work on Windows?  Is there another place I can get the latest release for Windows?

Output:

[07/15/2024 21:26 PM] "C:\Users\ajmia\Desktop\P5R Modding\CPKs\FIELD\INIT\FINI_009_003.BF" -Decompile   -Library P5R -Encoding P5R_EFIGS  -Hook  -SumBits 
[07/15/2024 21:26 PM] 7/15/2024 9:26:39 PM  Info: Using P5R_EFIGS encoding
[07/15/2024 21:26 PM] 7/15/2024 9:26:39 PM  Info: Output file path is set to C:\Users\ajmia\Desktop\P5R Modding\CPKs\FIELD\INIT\FINI_009_003.BF.flow
[07/15/2024 21:26 PM] 7/15/2024 9:26:39 PM  Info: Loading binary FlowScript file...
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Info: Decompiling FlowScript...
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error: Unhandled exception thrown
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error: Exception info:
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error: Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error: Stacktrace:
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error:    at AtlusScriptLibrary.Common.Libraries.LibraryLookup.ParseLibrary(String path)
[07/15/2024 21:26 PM]    at AtlusScriptLibrary.Common.Libraries.LibraryLookup.EnsureInitialized() in C:\projects\atlus-script-tools\Source\AtlusScriptLibrary\Common\Libraries\LibraryLookup.cs:line 38
[07/15/2024 21:26 PM]    at AtlusScriptLibrary.Common.Libraries.LibraryLookup.GetLibrary(String name) in C:\projects\atlus-script-tools\Source\AtlusScriptLibrary\Common\Libraries\LibraryLookup.cs:line 50
[07/15/2024 21:26 PM]    at AtlusScriptCompiler.Program.TryDoFlowScriptDecompilation() in C:\projects\atlus-script-tools\Source\AtlusScriptCompiler\Program.cs:line 767
[07/15/2024 21:26 PM]    at AtlusScriptCompiler.Program.TryDoDecompilation() in C:\projects\atlus-script-tools\Source\AtlusScriptCompiler\Program.cs:line 739
[07/15/2024 21:26 PM]    at AtlusScriptCompiler.Program.Main(String[] args) in C:\projects\atlus-script-tools\Source\AtlusScriptCompiler\Program.cs:line 167
[07/15/2024 21:26 PM] 7/15/2024 9:26:40 PM  Error: One or more errors occured while executing task!
[07/15/2024 21:26 PM]

**Comment by ajmiam** [comment]
Note: I was able to get around this by simply downloading the repository and building the solution in Visual Studio 2022.  Then I was able to point the Atlus Script GUI to the AtlusScriptCompiler.exe file in the Build folder and it worked fine.
